
var listObj = [
{
"id": 151,
"nodeid": 61,
"parentnodeid": 0,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "盈特集团",
"nodecode": "100",
"nodetype": 10,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 152,
"nodeid": 62,
"parentnodeid": 61,
"isorganizationnode": 1,
"parentnodename": "盈特集团",
"parentnodecode": "100",
"parentnodetype": 10,
"nodename": "佛山市盈特金属制品有限公司",
"nodecode": "100101",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 153,
"nodeid": 63,
"parentnodeid": 61,
"isorganizationnode": 1,
"parentnodename": "盈特集团",
"parentnodecode": "100",
"parentnodetype": 10,
"nodename": "邯郸市盈顺电器有限公司",
"nodecode": "100102",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 156,
"nodeid": 66,
"parentnodeid": 62,
"isorganizationnode": 1,
"parentnodename": "佛山市盈特金属制品有限公司",
"parentnodecode": "100101",
"parentnodetype": 20,
"nodename": "金属车间1",
"nodecode": "100101001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 157,
"nodeid": 67,
"parentnodeid": 62,
"isorganizationnode": 1,
"parentnodename": "佛山市盈特金属制品有限公司",
"parentnodecode": "100101",
"parentnodetype": 20,
"nodename": "金属车间2",
"nodecode": "100101002",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 172,
"nodeid": 39,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000001",
"device_name": "CNC06",
"icon": "/img/Group7.png"
},
{
"id": 175,
"nodeid": 45,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000002",
"device_name": "CNC12",
"icon": "/img/Group7.png"
},
{
"id": 176,
"nodeid": 46,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000003",
"device_name": "CNC13",
"icon": "/img/Group7.png"
},
{
"id": 177,
"nodeid": 49,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000004",
"device_name": "CNC16",
"icon": "/img/Group7.png"
},
{
"id": 178,
"nodeid": 34,
"parentnodeid": 67,
"isorganizationnode": 0,
"parentnodename": "金属车间2",
"parentnodecode": "100101002",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000001",
"device_name": "CNC01",
"icon": "/img/Group7.png"
},
{
"id": 217,
"nodeid": 70,
"parentnodeid": 67,
"isorganizationnode": 1,
"parentnodename": "金属车间2",
"parentnodecode": "100101002",
"parentnodetype": 30,
"nodename": "产线1",
"nodecode": "300300300444",
"nodetype": 40,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 224,
"nodeid": 2,
"parentnodeid": 71,
"isorganizationnode": 0,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 232,
"nodeid": 1,
"parentnodeid": 69,
"isorganizationnode": 0,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 233,
"nodeid": 2,
"parentnodeid": 69,
"isorganizationnode": 0,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 234,
"nodeid": 3,
"parentnodeid": 69,
"isorganizationnode": 0,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 256,
"nodeid": 94,
"parentnodeid": 63,
"isorganizationnode": 1,
"parentnodename": "邯郸市盈顺电器有限公司",
"parentnodecode": "100102",
"parentnodetype": 20,
"nodename": "电器车间1",
"nodecode": "0008",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 258,
"nodeid": 96,
"parentnodeid": 63,
"isorganizationnode": 1,
"parentnodename": "邯郸市盈顺电器有限公司",
"parentnodecode": "100102",
"parentnodetype": 20,
"nodename": "电器车间2",
"nodecode": "0009",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 262,
"nodeid": 54,
"parentnodeid": 94,
"isorganizationnode": 0,
"parentnodename": "电器车间1",
"parentnodecode": "0008",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000005",
"device_name": "CNC21",
"icon": "/img/Group7.png"
},
{
"id": 264,
"nodeid": 45,
"parentnodeid": 94,
"isorganizationnode": 0,
"parentnodename": "电器车间1",
"parentnodecode": "0008",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000002",
"device_name": "CNC12",
"icon": "/img/Group7.png"
},
{
"id": 265,
"nodeid": 1,
"parentnodeid": 94,
"isorganizationnode": 0,
"parentnodename": "电器车间1",
"parentnodecode": "0008",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 266,
"nodeid": 4,
"parentnodeid": 94,
"isorganizationnode": 0,
"parentnodename": "电器车间1",
"parentnodecode": "0008",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000004",
"device_name": "NC10",
"icon": "/img/Group7.png"
},
{
"id": 267,
"nodeid": 39,
"parentnodeid": 94,
"isorganizationnode": 0,
"parentnodename": "电器车间1",
"parentnodecode": "0008",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000001",
"device_name": "CNC06",
"icon": "/img/Group7.png"
},
{
"id": 268,
"nodeid": 100,
"parentnodeid": 94,
"isorganizationnode": 1,
"parentnodename": "电器车间1",
"parentnodecode": "0008",
"parentnodetype": 30,
"nodename": "汪汪产线一",
"nodecode": "100880",
"nodetype": 40,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 269,
"nodeid": 1,
"parentnodeid": 100,
"isorganizationnode": 0,
"parentnodename": "汪汪产线一",
"parentnodecode": "100880",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 270,
"nodeid": 2,
"parentnodeid": 100,
"isorganizationnode": 0,
"parentnodename": "汪汪产线一",
"parentnodecode": "100880",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 271,
"nodeid": 35,
"parentnodeid": 100,
"isorganizationnode": 0,
"parentnodename": "汪汪产线一",
"parentnodecode": "100880",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000002",
"device_name": "CNC02",
"icon": "/img/Group7.png"
},
{
"id": 272,
"nodeid": 101,
"parentnodeid": 94,
"isorganizationnode": 1,
"parentnodename": "电器车间1",
"parentnodecode": "0008",
"parentnodetype": 30,
"nodename": "汪汪产线二",
"nodecode": "100811",
"nodetype": 40,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 278,
"nodeid": 106,
"parentnodeid": 99,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "汪一股份有限公司",
"nodecode": "888881",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 279,
"nodeid": 3,
"parentnodeid": 100,
"isorganizationnode": 0,
"parentnodename": "汪汪产线一",
"parentnodecode": "100880",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 281,
"nodeid": 4,
"parentnodeid": 100,
"isorganizationnode": 0,
"parentnodename": "汪汪产线一",
"parentnodecode": "100880",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000004",
"device_name": "NC10",
"icon": "/img/Group7.png"
},
{
"id": 282,
"nodeid": 39,
"parentnodeid": 100,
"isorganizationnode": 0,
"parentnodename": "汪汪产线一",
"parentnodecode": "100880",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000001",
"device_name": "CNC06",
"icon": "/img/Group7.png"
},
{
"id": 283,
"nodeid": 107,
"parentnodeid": 0,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "阳江市太仕模具有限公司",
"nodecode": "0001",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 284,
"nodeid": 108,
"parentnodeid": 0,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "顺德市科尔技术发展有限公司",
"nodecode": "0002",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 286,
"nodeid": 110,
"parentnodeid": 0,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "机器人企业",
"nodecode": "0004",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 288,
"nodeid": 112,
"parentnodeid": 0,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "杰为软件",
"nodecode": "0007",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 289,
"nodeid": 113,
"parentnodeid": 107,
"isorganizationnode": 1,
"parentnodename": "阳江市太仕模具有限公司",
"parentnodecode": "0001",
"parentnodetype": 20,
"nodename": "模具车间一",
"nodecode": "TESTMJ1",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 307,
"nodeid": 120,
"parentnodeid": 112,
"isorganizationnode": 1,
"parentnodename": "杰为软件",
"parentnodecode": "0007",
"parentnodetype": 20,
"nodename": "杰为车间",
"nodecode": "A001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 311,
"nodeid": 1,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 312,
"nodeid": 2,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 313,
"nodeid": 3,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 314,
"nodeid": 4,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000004",
"device_name": "NC10",
"icon": "/img/Group7.png"
},
{
"id": 315,
"nodeid": 39,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000001",
"device_name": "CNC06",
"icon": "/img/Group7.png"
},
{
"id": 316,
"nodeid": 45,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000002",
"device_name": "CNC12",
"icon": "/img/Group7.png"
},
{
"id": 317,
"nodeid": 46,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000003",
"device_name": "CNC13",
"icon": "/img/Group7.png"
},
{
"id": 318,
"nodeid": 49,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000004",
"device_name": "CNC16",
"icon": "/img/Group7.png"
},
{
"id": 319,
"nodeid": 89,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000300004000001",
"device_name": "zhusuji1",
"icon": "/img/mes.png"
},
{
"id": 320,
"nodeid": 152,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000400005000001",
"device_name": "RobotA",
"icon": "/img/u_robot.png"
},
{
"id": 321,
"nodeid": 34,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000001",
"device_name": "CNC01",
"icon": "/img/Group7.png"
},
{
"id": 322,
"nodeid": 35,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000002",
"device_name": "CNC02",
"icon": "/img/Group7.png"
},
{
"id": 323,
"nodeid": 42,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000003",
"device_name": "CNC09",
"icon": "/img/Group7.png"
},
{
"id": 324,
"nodeid": 43,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000004",
"device_name": "CNC10",
"icon": "/img/Group7.png"
},
{
"id": 325,
"nodeid": 47,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000005",
"device_name": "CNC14",
"icon": "/img/Group7.png"
},
{
"id": 326,
"nodeid": 48,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000006",
"device_name": "CNC15",
"icon": "/img/Group7.png"
},
{
"id": 327,
"nodeid": 54,
"parentnodeid": 120,
"isorganizationnode": 0,
"parentnodename": "杰为车间",
"parentnodecode": "A001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000005",
"device_name": "CNC21",
"icon": "/img/Group7.png"
},
{
"id": 328,
"nodeid": 121,
"parentnodeid": 109,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "注塑车间一",
"nodecode": "ZS001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 329,
"nodeid": 89,
"parentnodeid": 121,
"isorganizationnode": 0,
"parentnodename": "注塑车间一",
"parentnodecode": "ZS001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000300004000001",
"device_name": "zhusuji1",
"icon": "/img/mes.png"
},
{
"id": 330,
"nodeid": 122,
"parentnodeid": 110,
"isorganizationnode": 1,
"parentnodename": "机器人企业",
"parentnodecode": "0004",
"parentnodetype": 20,
"nodename": "机器车间一",
"nodecode": "Rotbot001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 331,
"nodeid": 152,
"parentnodeid": 122,
"isorganizationnode": 0,
"parentnodename": "机器车间一",
"parentnodecode": "Rotbot001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000400005000001",
"device_name": "RobotA",
"icon": "/img/u_robot.png"
},
{
"id": 332,
"nodeid": 123,
"parentnodeid": 111,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "摄像头车间一",
"nodecode": "Camera001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 333,
"nodeid": 124,
"parentnodeid": 115,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "默认车间一",
"nodecode": "MO001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 334,
"nodeid": 125,
"parentnodeid": 124,
"isorganizationnode": 1,
"parentnodename": "默认车间一",
"parentnodecode": "MO001",
"parentnodetype": 30,
"nodename": "产线一",
"nodecode": "CX001",
"nodetype": 40,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 335,
"nodeid": 1,
"parentnodeid": 125,
"isorganizationnode": 0,
"parentnodename": "产线一",
"parentnodecode": "CX001",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 336,
"nodeid": 2,
"parentnodeid": 125,
"isorganizationnode": 0,
"parentnodename": "产线一",
"parentnodecode": "CX001",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 337,
"nodeid": 126,
"parentnodeid": 124,
"isorganizationnode": 1,
"parentnodename": "默认车间一",
"parentnodecode": "MO001",
"parentnodetype": 30,
"nodename": "产线二",
"nodecode": "CX002",
"nodetype": 40,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 338,
"nodeid": 3,
"parentnodeid": 126,
"isorganizationnode": 0,
"parentnodename": "产线二",
"parentnodecode": "CX002",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 339,
"nodeid": 1,
"parentnodeid": 126,
"isorganizationnode": 0,
"parentnodename": "产线二",
"parentnodecode": "CX002",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 340,
"nodeid": 4,
"parentnodeid": 126,
"isorganizationnode": 0,
"parentnodename": "产线二",
"parentnodecode": "CX002",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000004",
"device_name": "NC10",
"icon": "/img/Group7.png"
},
{
"id": 341,
"nodeid": 4,
"parentnodeid": 125,
"isorganizationnode": 0,
"parentnodename": "产线一",
"parentnodecode": "CX001",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000004",
"device_name": "NC10",
"icon": "/img/Group7.png"
},
{
"id": 342,
"nodeid": 39,
"parentnodeid": 125,
"isorganizationnode": 0,
"parentnodename": "产线一",
"parentnodecode": "CX001",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000001",
"device_name": "CNC06",
"icon": "/img/Group7.png"
},
{
"id": 343,
"nodeid": 45,
"parentnodeid": 125,
"isorganizationnode": 0,
"parentnodename": "产线一",
"parentnodecode": "CX001",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000002",
"device_name": "CNC12",
"icon": "/img/Group7.png"
},
{
"id": 344,
"nodeid": 46,
"parentnodeid": 125,
"isorganizationnode": 0,
"parentnodename": "产线一",
"parentnodecode": "CX001",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000003",
"device_name": "CNC13",
"icon": "/img/Group7.png"
},
{
"id": 345,
"nodeid": 49,
"parentnodeid": 125,
"isorganizationnode": 0,
"parentnodename": "产线一",
"parentnodecode": "CX001",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000004",
"device_name": "CNC16",
"icon": "/img/Group7.png"
},
{
"id": 346,
"nodeid": 34,
"parentnodeid": 126,
"isorganizationnode": 0,
"parentnodename": "产线二",
"parentnodecode": "CX002",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000001",
"device_name": "CNC01",
"icon": "/img/Group7.png"
},
{
"id": 347,
"nodeid": 35,
"parentnodeid": 126,
"isorganizationnode": 0,
"parentnodename": "产线二",
"parentnodecode": "CX002",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000002",
"device_name": "CNC02",
"icon": "/img/Group7.png"
},
{
"id": 348,
"nodeid": 2,
"parentnodeid": 126,
"isorganizationnode": 0,
"parentnodename": "产线二",
"parentnodecode": "CX002",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 349,
"nodeid": 42,
"parentnodeid": 126,
"isorganizationnode": 0,
"parentnodename": "产线二",
"parentnodecode": "CX002",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000003",
"device_name": "CNC09",
"icon": "/img/Group7.png"
},
{
"id": 350,
"nodeid": 1,
"parentnodeid": 113,
"isorganizationnode": 0,
"parentnodename": "模具车间一",
"parentnodecode": "TESTMJ1",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 351,
"nodeid": 2,
"parentnodeid": 113,
"isorganizationnode": 0,
"parentnodename": "模具车间一",
"parentnodecode": "TESTMJ1",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 352,
"nodeid": 3,
"parentnodeid": 113,
"isorganizationnode": 0,
"parentnodename": "模具车间一",
"parentnodecode": "TESTMJ1",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 353,
"nodeid": 4,
"parentnodeid": 113,
"isorganizationnode": 0,
"parentnodename": "模具车间一",
"parentnodecode": "TESTMJ1",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000004",
"device_name": "NC10",
"icon": "/img/Group7.png"
},
{
"id": 354,
"nodeid": 127,
"parentnodeid": 108,
"isorganizationnode": 1,
"parentnodename": "顺德市科尔技术发展有限公司",
"parentnodecode": "0002",
"parentnodetype": 20,
"nodename": "Koer模具车间",
"nodecode": "Koer001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 355,
"nodeid": 34,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000001",
"device_name": "CNC01",
"icon": "/img/Group7.png"
},
{
"id": 356,
"nodeid": 35,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000002",
"device_name": "CNC02",
"icon": "/img/Group7.png"
},
{
"id": 357,
"nodeid": 39,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000001",
"device_name": "CNC06",
"icon": "/img/Group7.png"
},
{
"id": 358,
"nodeid": 42,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000003",
"device_name": "CNC09",
"icon": "/img/Group7.png"
},
{
"id": 359,
"nodeid": 43,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000004",
"device_name": "CNC10",
"icon": "/img/Group7.png"
},
{
"id": 360,
"nodeid": 45,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000002",
"device_name": "CNC12",
"icon": "/img/Group7.png"
},
{
"id": 361,
"nodeid": 46,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000003",
"device_name": "CNC13",
"icon": "/img/Group7.png"
},
{
"id": 362,
"nodeid": 47,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000005",
"device_name": "CNC14",
"icon": "/img/Group7.png"
},
{
"id": 363,
"nodeid": 48,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000006",
"device_name": "CNC15",
"icon": "/img/Group7.png"
},
{
"id": 364,
"nodeid": 49,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000004",
"device_name": "CNC16",
"icon": "/img/Group7.png"
},
{
"id": 365,
"nodeid": 54,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000005",
"device_name": "CNC21",
"icon": "/img/Group7.png"
},
{
"id": 377,
"nodeid": 1,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 378,
"nodeid": 2,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 379,
"nodeid": 3,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 380,
"nodeid": 4,
"parentnodeid": 127,
"isorganizationnode": 0,
"parentnodename": "Koer模具车间",
"parentnodecode": "Koer001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000004",
"device_name": "NC10",
"icon": "/img/Group7.png"
},
{
"id": 381,
"nodeid": 1,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 382,
"nodeid": 2,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 383,
"nodeid": 3,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 384,
"nodeid": 4,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000004",
"device_name": "NC10",
"icon": "/img/Group7.png"
},
{
"id": 385,
"nodeid": 34,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000001",
"device_name": "CNC01",
"icon": "/img/Group7.png"
},
{
"id": 386,
"nodeid": 42,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000003",
"device_name": "CNC09",
"icon": "/img/Group7.png"
},
{
"id": 387,
"nodeid": 35,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000002",
"device_name": "CNC02",
"icon": "/img/Group7.png"
},
{
"id": 388,
"nodeid": 43,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000004",
"device_name": "CNC10",
"icon": "/img/Group7.png"
},
{
"id": 389,
"nodeid": 47,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000005",
"device_name": "CNC14",
"icon": "/img/Group7.png"
},
{
"id": 390,
"nodeid": 48,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000006",
"device_name": "CNC15",
"icon": "/img/Group7.png"
},
{
"id": 391,
"nodeid": 54,
"parentnodeid": 66,
"isorganizationnode": 0,
"parentnodename": "金属车间1",
"parentnodecode": "100101001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000005",
"device_name": "CNC21",
"icon": "/img/Group7.png"
},
{
"id": 394,
"nodeid": 1,
"parentnodeid": 70,
"isorganizationnode": 0,
"parentnodename": "产线1",
"parentnodecode": "300300300444",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 395,
"nodeid": 130,
"parentnodeid": 106,
"isorganizationnode": 1,
"parentnodename": "汪一股份有限公司",
"parentnodecode": "888881",
"parentnodetype": 20,
"nodename": "汪一车间",
"nodecode": "001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 398,
"nodeid": 54,
"parentnodeid": 130,
"isorganizationnode": 0,
"parentnodename": "汪一车间",
"parentnodecode": "001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000005",
"device_name": "CNC21",
"icon": "/img/Group7.png"
},
{
"id": 400,
"nodeid": 45,
"parentnodeid": 130,
"isorganizationnode": 0,
"parentnodename": "汪一车间",
"parentnodecode": "001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000002",
"device_name": "CNC12",
"icon": "/img/Group7.png"
},
{
"id": 401,
"nodeid": 45,
"parentnodeid": 101,
"isorganizationnode": 0,
"parentnodename": "汪汪产线二",
"parentnodecode": "100811",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000002",
"device_name": "CNC12",
"icon": "/img/Group7.png"
},
{
"id": 402,
"nodeid": 46,
"parentnodeid": 101,
"isorganizationnode": 0,
"parentnodename": "汪汪产线二",
"parentnodecode": "100811",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000003",
"device_name": "CNC13",
"icon": "/img/Group7.png"
},
{
"id": 403,
"nodeid": 54,
"parentnodeid": 101,
"isorganizationnode": 0,
"parentnodename": "汪汪产线二",
"parentnodecode": "100811",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000005",
"device_name": "CNC21",
"icon": "/img/Group7.png"
},
{
"id": 412,
"nodeid": 45,
"parentnodeid": 96,
"isorganizationnode": 0,
"parentnodename": "电器车间2",
"parentnodecode": "0009",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000002",
"device_name": "CNC12",
"icon": "/img/Group7.png"
},
{
"id": 413,
"nodeid": 3,
"parentnodeid": 96,
"isorganizationnode": 0,
"parentnodename": "电器车间2",
"parentnodecode": "0009",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 414,
"nodeid": 49,
"parentnodeid": 96,
"isorganizationnode": 0,
"parentnodename": "电器车间2",
"parentnodecode": "0009",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000004",
"device_name": "CNC16",
"icon": "/img/Group7.png"
},
{
"id": 418,
"nodeid": 43,
"parentnodeid": 130,
"isorganizationnode": 0,
"parentnodename": "汪一车间",
"parentnodecode": "001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200003000004",
"device_name": "CNC10",
"icon": "/img/Group7.png"
},
{
"id": 419,
"nodeid": 173,
"parentnodeid": 130,
"isorganizationnode": 0,
"parentnodename": "汪一车间",
"parentnodecode": "001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100013000059",
"device_name": "Camera",
"icon": "/img/cam.png"
},
{
"id": 422,
"nodeid": 139,
"parentnodeid": 67,
"isorganizationnode": 1,
"parentnodename": "金属车间2",
"parentnodecode": "100101002",
"parentnodetype": 30,
"nodename": "产线5",
"nodecode": "2",
"nodetype": 40,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 423,
"nodeid": 49,
"parentnodeid": 139,
"isorganizationnode": 0,
"parentnodename": "产线5",
"parentnodecode": "2",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000004",
"device_name": "CNC16",
"icon": "/img/Group7.png"
},
{
"id": 470,
"nodeid": 173,
"parentnodeid": 123,
"isorganizationnode": 0,
"parentnodename": "摄像头车间一",
"parentnodecode": "Camera001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100013000059",
"device_name": "Camera",
"icon": "/img/cam.png"
},
{
"id": 471,
"nodeid": 3,
"parentnodeid": 130,
"isorganizationnode": 0,
"parentnodename": "汪一车间",
"parentnodecode": "001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000003",
"device_name": "NC09",
"icon": "/img/Group7.png"
},
{
"id": 472,
"nodeid": 1,
"parentnodeid": 130,
"isorganizationnode": 0,
"parentnodename": "汪一车间",
"parentnodecode": "001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 488,
"nodeid": 162,
"parentnodeid": 0,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "集团A",
"nodecode": "010",
"nodetype": 10,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 489,
"nodeid": 163,
"parentnodeid": 162,
"isorganizationnode": 1,
"parentnodename": "集团A",
"parentnodecode": "010",
"parentnodetype": 10,
"nodename": "工厂01",
"nodecode": "011",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 490,
"nodeid": 164,
"parentnodeid": 163,
"isorganizationnode": 1,
"parentnodename": "工厂01",
"parentnodecode": "011",
"parentnodetype": 20,
"nodename": "SMT车间01",
"nodecode": "0110",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 491,
"nodeid": 165,
"parentnodeid": 164,
"isorganizationnode": 1,
"parentnodename": "SMT车间01",
"parentnodecode": "0110",
"parentnodetype": 30,
"nodename": "SMT产线",
"nodecode": "SMT01",
"nodetype": 40,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 492,
"nodeid": 198,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000700016495536",
"device_name": "Printer",
"icon": "/img/cam.png"
},
{
"id": 494,
"nodeid": 203,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000700016670111",
"device_name": "AOI01",
"icon": "/img/cam.png"
},
{
"id": 495,
"nodeid": 204,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "0007000164106",
"device_name": "AOI02",
"icon": "/img/cam.png"
},
{
"id": 497,
"nodeid": 205,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000700016734346",
"device_name": "Reflow",
"icon": "/img/cam.png"
},
{
"id": 498,
"nodeid": 199,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000700016910801",
"device_name": "SPI",
"icon": "/img/cam.png"
},
{
"id": 509,
"nodeid": 172,
"parentnodeid": 0,
"isorganizationnode": 1,
"parentnodename": null,
"parentnodecode": null,
"parentnodetype": null,
"nodename": "广东星徽精密制造股份有限公司",
"nodecode": "0000888",
"nodetype": 20,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 510,
"nodeid": 173,
"parentnodeid": 172,
"isorganizationnode": 1,
"parentnodename": "广东星徽精密制造股份有限公司",
"parentnodecode": "0000888",
"parentnodetype": 20,
"nodename": "星徽车间",
"nodecode": "xh001",
"nodetype": 30,
"device_code": null,
"device_name": null,
"icon": null
},
{
"id": 513,
"nodeid": 1,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000001",
"device_name": "NC01",
"icon": "/img/Group7.png"
},
{
"id": 517,
"nodeid": 2,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100001000002",
"device_name": "NC02",
"icon": "/img/Group7.png"
},
{
"id": 519,
"nodeid": 202,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000700016189475",
"device_name": "Mounter03",
"icon": "/img/cam.png"
},
{
"id": 520,
"nodeid": 39,
"parentnodeid": 165,
"isorganizationnode": 0,
"parentnodename": "SMT产线",
"parentnodecode": "SMT01",
"parentnodetype": 40,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000200001000001",
"device_name": "CNC06",
"icon": "/img/Group7.png"
},
{
"id": 527,
"nodeid": 214,
"parentnodeid": 173,
"isorganizationnode": 0,
"parentnodename": "星徽车间",
"parentnodecode": "xh001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "088800017690862",
"device_name": "XHRobot",
"icon": "/img/u_robot.png"
},
{
"id": 528,
"nodeid": 215,
"parentnodeid": 173,
"isorganizationnode": 0,
"parentnodename": "星徽车间",
"parentnodecode": "xh001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "088800018177621",
"device_name": "XHpunch",
"icon": "/img/Group7.png"
},
{
"id": 529,
"nodeid": 212,
"parentnodeid": 173,
"isorganizationnode": 0,
"parentnodename": "星徽车间",
"parentnodecode": "xh001",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "088800001185800",
"device_name": "XHCNC01",
"icon": "/img/Group7.png"
},
{
"id": 530,
"nodeid": 173,
"parentnodeid": 113,
"isorganizationnode": 0,
"parentnodename": "模具车间一",
"parentnodecode": "TESTMJ1",
"parentnodetype": 30,
"nodename": null,
"nodecode": null,
"nodetype": null,
"device_code": "000100013000059",
"device_name": "Camera",
"icon": "/img/cam.png"
}
]

export default listObj;